export { default as UsersManagementPage } from './UsersManagementPage'
export { default as UserDetailPage } from './UserDetailPage'
export { default as CreateUserPage } from './CreateUserPage'
export { default as AllTransactionsPage } from './AllTransactionsPage'
export { default as PromotionsManagementPage } from './PromotionsManagementPage'
export { default as CreatePromotionPage } from './CreatePromotionPage'
export { default as EventsManagementPage } from './EventsManagementPage'
export { default as CreateEventPage } from './CreateEventPage'
export { default as AnalyticsPage } from './AnalyticsPage'

